<?php

namespace SearchBundle\Repository;
use SearchBundle\SearchBundle;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function getByTags($tags){
        /*
        $repository =  $this->getDoctrine()->getRepository(SearchBundle::Produit);
        for($i = 0; $i< count($tags); $i++) {
            $products = $repository->findBy([
                'tags' => $tags
            ]);
            for (;$i2<count($products); $i2++) {
                $tabReturn[$i2] = var_dump($products[$i2]);
                }
            }
            return $tabReturn;
        }*/
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where(':tag MEMBER OF p.tags')
            ->setParameter('tag', $tags)
            ->getQuery()
            ->getResult();
        /*foreach($tags as $tag){
            $products = $repository->findBy([
                'tags' => $tags
            ]);
        }*/
    }
}
