core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

search:
    resource: "@SearchBundle/Controller/"
    type:     annotation
    prefix:   /search

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
