core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

search:
    resource: "@SearchBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
