services:
#    search.example:
#        class: SearchBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    SearchBundle\DataFixtures\ORM\loadEcoSearch:
        tags: [doctrine.fixture.orm]